apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../cloud-generic
patchesStrategicMerge:
- service-l7.yaml
configMapGenerator:
- name: nginx-configuration
  behavior: merge
  literals:
  - use-proxy-protocol=false
  - use-forwarded-headers=true
  - proxy-real-ip-cidr=0.0.0.0/0 # restrict this to the IP addresses of ELB
